import {
  AMAURA_CONSUMERS,
  AMAURA_EVENT_MATRIX,
  AMAURA_EVENTS,
} from '@/lib/amaura/events/event-matrix';

export const DOWNSTREAM_CONSUMER = 'downstream_publisher_qstash' as const;

export const EVENT_CONSUMERS = [
  DOWNSTREAM_CONSUMER,
  ...AMAURA_CONSUMERS,
] as const;

export type EventConsumer = typeof EVENT_CONSUMERS[number];

const downstreamOnly = [DOWNSTREAM_CONSUMER] as const;

export const EVENT_CONSUMER_MATRIX: Record<string, readonly EventConsumer[]> = {
  AUTOPSY_V3_REPORT_READY: [
    ...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AUTOPSY_V3_REPORT_READY],
    DOWNSTREAM_CONSUMER,
  ],
  PRACTICE_ATTEMPT_SUBMITTED: ['amaura_practice_agent', DOWNSTREAM_CONSUMER],
  PRACTICE_ATTEMPT_RECORDED: ['amaura_practice_agent', DOWNSTREAM_CONSUMER],
  STUDY_SESSION_COMPLETED: ['amaura_session_agent', DOWNSTREAM_CONSUMER],
  SESSION_CLOSED: [
    ...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.SESSION_CLOSED],
    DOWNSTREAM_CONSUMER,
  ],
  STUDENT_MODEL_SYNC_REQUESTED: [
    'amaura_forgetting_agent',
    'amaura_stagnation_agent',
    'amaura_pattern_memory',
    DOWNSTREAM_CONSUMER,
  ],
  FORGETTING_SCAN_REQUESTED: ['amaura_forgetting_agent', DOWNSTREAM_CONSUMER],
  STAGNATION_SCAN_REQUESTED: ['amaura_stagnation_agent', DOWNSTREAM_CONSUMER],
  PATTERN_MEMORY_SCAN_REQUESTED: ['amaura_pattern_memory', DOWNSTREAM_CONSUMER],
  DAILY_AGENT_TICK: [
    ...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.DAILY_AGENT_TICK],
    DOWNSTREAM_CONSUMER,
  ],
  AMAURA_GOAL_CREATED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AMAURA_GOAL_CREATED], DOWNSTREAM_CONSUMER],
  AMAURA_GOAL_UPDATED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AMAURA_GOAL_UPDATED], DOWNSTREAM_CONSUMER],
  AMAURA_TASK_CREATED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AMAURA_TASK_CREATED], DOWNSTREAM_CONSUMER],
  AMAURA_TASK_COMPLETED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AMAURA_TASK_COMPLETED], DOWNSTREAM_CONSUMER],
  AMAURA_TASK_SKIPPED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AMAURA_TASK_SKIPPED], DOWNSTREAM_CONSUMER],
  AMAURA_OBSERVATION_RECORDED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AMAURA_OBSERVATION_RECORDED], DOWNSTREAM_CONSUMER],
  AMAURA_PLAN_ADAPTED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AMAURA_PLAN_ADAPTED], DOWNSTREAM_CONSUMER],
  AMAURA_GOAL_PROGRESS_EVALUATED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.AMAURA_GOAL_PROGRESS_EVALUATED], DOWNSTREAM_CONSUMER],
  MEMORY_REVIEW_COMPLETED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.MEMORY_REVIEW_COMPLETED], DOWNSTREAM_CONSUMER],
  ATLAS_CONCEPT_UPDATED: [...AMAURA_EVENT_MATRIX[AMAURA_EVENTS.ATLAS_CONCEPT_UPDATED], DOWNSTREAM_CONSUMER],
};

export function getConsumersForEvent(type: string): readonly EventConsumer[] {
  return EVENT_CONSUMER_MATRIX[type] ?? downstreamOnly;
}

export function assertEventConsumerRoute(type: string, consumer: string): asserts consumer is EventConsumer {
  const expected = getConsumersForEvent(type);
  if (!expected.includes(consumer as EventConsumer)) {
    throw new Error(`Event routing error: ${consumer} is not registered for ${type}`);
  }
}
