import type { SeedTemplate } from '../types';
export const NEET_BIOLOGY_TEMPLATES: SeedTemplate[] = [
  {
    templateKey: 'neet_biology_human_reproduction',
    subject: 'Biology',
    chapter: 'Human Reproduction',
    displayName: 'Human Reproduction',
    aliases: ['human reproduction', 'male reproductive system', 'female reproductive system', 'menstrual cycle', 'fertilisation', 'fertilization'],
    topics: [
      { orderIndex: 1, topic: 'Male reproductive system', microtarget: 'Identify organs, ducts, glands, and their functions in the male reproductive system.' },
      { orderIndex: 2, topic: 'Spermatogenesis', microtarget: 'Understand stages, location, hormones, and outcome of spermatogenesis.' },
      { orderIndex: 3, topic: 'Sperm structure', microtarget: 'Identify head, middle piece, tail, acrosome, and mitochondria role.' },
      { orderIndex: 4, topic: 'Female reproductive system', microtarget: 'Identify ovary, oviduct, uterus, cervix, vagina, and external genitalia.' },
      { orderIndex: 5, topic: 'Oogenesis', microtarget: 'Understand stages and timing of oogenesis.' },
      { orderIndex: 6, topic: 'Menstrual cycle', microtarget: 'Master menstrual, follicular, ovulatory, and luteal phases with hormones.' },
      { orderIndex: 7, topic: 'Fertilisation', microtarget: 'Understand capacitation, acrosome reaction, and fusion of gametes.' },
      { orderIndex: 8, topic: 'Implantation and pregnancy', microtarget: 'Understand blastocyst implantation, placenta, and pregnancy hormones.' },
      { orderIndex: 9, topic: 'Parturition and lactation', microtarget: 'Understand oxytocin, labour reflex, colostrum, and lactation.' },
      { orderIndex: 10, topic: 'NCERT diagram facts', microtarget: 'Revise NCERT diagrams and labels from Human Reproduction.' },
      { orderIndex: 11, topic: 'Common reproduction mistakes', microtarget: 'Avoid hormone sequence and gametogenesis timeline mistakes.' },
    ],
  },
  {
    templateKey: 'neet_biology_plant_reproduction',
    subject: 'Biology',
    chapter: 'Sexual Reproduction in Flowering Plants',
    displayName: 'Sexual Reproduction in Flowering Plants',
    aliases: ['sexual reproduction in flowering plants', 'flowering plants reproduction', 'pollination', 'double fertilisation', 'double fertilization'],
    topics: [
      { orderIndex: 1, topic: 'Flower structure', microtarget: 'Identify reproductive parts of flower and their functions.' },
      { orderIndex: 2, topic: 'Microsporogenesis', microtarget: 'Understand formation of microspores and pollen grains.' },
      { orderIndex: 3, topic: 'Megasporogenesis', microtarget: 'Understand formation of embryo sac and female gametophyte.' },
      { orderIndex: 4, topic: 'Pollination', microtarget: 'Compare autogamy, geitonogamy, xenogamy, and pollination agents.' },
      { orderIndex: 5, topic: 'Pollen-pistil interaction', microtarget: 'Understand compatibility, pollen tube growth, and guidance.' },
      { orderIndex: 6, topic: 'Double fertilisation', microtarget: 'Master syngamy, triple fusion, zygote, and PEN formation.' },
      { orderIndex: 7, topic: 'Seed and fruit formation', microtarget: 'Understand seed, fruit, endosperm, and embryo development.' },
      { orderIndex: 8, topic: 'Apomixis and polyembryony', microtarget: 'Understand special modes of reproduction and their significance.' },
      { orderIndex: 9, topic: 'NCERT diagram facts', microtarget: 'Revise diagrams of anther, ovule, embryo sac, and pollen grain.' },
    ],
  },
  {
    templateKey: 'neet_biology_genetics',
    subject: 'Biology',
    chapter: 'Principles of Inheritance and Variation',
    displayName: 'Genetics',
    aliases: ['genetics', 'inheritance', 'mendel', 'variation', 'pedigree', 'linkage'],
    topics: [
      { orderIndex: 1, topic: 'Mendel’s laws', microtarget: 'Understand law of dominance, segregation, and independent assortment.' },
      { orderIndex: 2, topic: 'Monohybrid cross', microtarget: 'Solve genotype and phenotype ratios in monohybrid crosses.' },
      { orderIndex: 3, topic: 'Dihybrid cross', microtarget: 'Solve dihybrid crosses and 9:3:3:1 ratio.' },
      { orderIndex: 4, topic: 'Incomplete dominance and codominance', microtarget: 'Differentiate incomplete dominance, codominance, and multiple alleles.' },
      { orderIndex: 5, topic: 'Sex determination', microtarget: 'Understand XX-XY, XO, ZW, and haplodiploid systems.' },
      { orderIndex: 6, topic: 'Pedigree analysis', microtarget: 'Identify autosomal dominant, autosomal recessive, and sex-linked inheritance.' },
      { orderIndex: 7, topic: 'Linkage and recombination', microtarget: 'Understand linked genes and recombination frequency.' },
      { orderIndex: 8, topic: 'Genetic disorders', microtarget: 'Revise examples of Mendelian and chromosomal disorders.' },
      { orderIndex: 9, topic: 'Common genetics mistakes', microtarget: 'Avoid ratio, pedigree, and dominance interpretation errors.' },
    ],
  },
  {
    templateKey: 'neet_biology_biotechnology',
    subject: 'Biology',
    chapter: 'Biotechnology: Principles and Processes',
    displayName: 'Biotechnology',
    aliases: ['biotechnology', 'biotech', 'biotechnology principles and processes', 'biotechnology and its applications', 'recombinant dna technology', 'r-dna technology', 'genetic engineering'],
    topics: [
      { orderIndex: 1, topic: 'Restriction enzymes', microtarget: 'Understand source, recognition site, sticky/blunt ends, and nomenclature.' },
      { orderIndex: 2, topic: 'Cloning vectors', microtarget: 'Understand ori, selectable marker, cloning sites, and pBR322.' },
      { orderIndex: 3, topic: 'Polymerase Chain Reaction (PCR)', microtarget: 'Master denaturation, annealing, extension, and Taq polymerase role.' },
      { orderIndex: 4, topic: 'Gel electrophoresis', microtarget: 'Understand DNA movement, EtBr staining, UV exposure, and elution.' },
      { orderIndex: 5, topic: 'Bioreactors', microtarget: 'Identify parts and conditions of simple and sparged stirred-tank bioreactors.' },
      { orderIndex: 6, topic: 'Downstream processing', microtarget: 'Understand separation and purification of products.' },
      { orderIndex: 7, topic: 'Bt cotton', microtarget: 'Understand cry gene, protoxin, and alkaline gut activation.' },
      { orderIndex: 8, topic: 'Gene therapy', microtarget: 'Revise ADA deficiency example and retroviral vectors.' },
      { orderIndex: 9, topic: 'ELISA and Diagnostics', microtarget: 'Understand antigen-antibody interaction principle and PCR in early diagnosis.' },
      { orderIndex: 10, topic: 'RNA interference (RNAi)', microtarget: 'Understand nematode resistance in tobacco plants via RNAi.' },
    ],
  },
];
