import type { SeedTemplate } from '../types';
export const NEET_CHEMISTRY_TEMPLATES: SeedTemplate[] = [
  {
    templateKey: 'neet_chemistry_mole_concept',
    subject: 'Chemistry',
    chapter: 'Some Basic Concepts of Chemistry',
    displayName: 'Mole Concept',
    aliases: ['mole concept', 'some basic concepts of chemistry', 'stoichiometry', 'molar mass', 'limiting reagent'],
    topics: [
      { orderIndex: 1, topic: 'Mole and Avogadro number', microtarget: 'Convert between moles, particles, atoms, molecules, and ions.' },
      { orderIndex: 2, topic: 'Atomic and molecular mass', microtarget: 'Calculate atomic mass, molecular mass, and formula mass.' },
      { orderIndex: 3, topic: 'Percentage composition', microtarget: 'Calculate mass percentage of elements in compounds.' },
      { orderIndex: 4, topic: 'Empirical and molecular formula', microtarget: 'Find empirical and molecular formula from percentage composition.' },
      { orderIndex: 5, topic: 'Stoichiometric calculations', microtarget: 'Use balanced equations to calculate moles and masses.' },
      { orderIndex: 6, topic: 'Limiting reagent', microtarget: 'Identify limiting reagent and calculate product formed.' },
      { orderIndex: 7, topic: 'Concentration terms', microtarget: 'Use molarity, molality, mole fraction, and mass percentage.' },
      { orderIndex: 8, topic: 'Common mole concept mistakes', microtarget: 'Avoid unit conversion and coefficient mistakes.' },
    ],
  },
  {
    templateKey: 'neet_chemistry_chemical_bonding',
    subject: 'Chemistry',
    chapter: 'Chemical Bonding',
    displayName: 'Chemical Bonding',
    aliases: ['chemical bonding', 'vsepr', 'hybridisation', 'hybridization', 'molecular orbital', 'bond order'],
    topics: [
      { orderIndex: 1, topic: 'Octet rule and exceptions', microtarget: 'Identify octet rule, incomplete octet, expanded octet, and odd-electron species.' },
      { orderIndex: 2, topic: 'Ionic bond', microtarget: 'Understand ionic bond formation and lattice energy trends.' },
      { orderIndex: 3, topic: 'Covalent bond', microtarget: 'Understand covalent bonding, bond length, bond angle, and bond energy.' },
      { orderIndex: 4, topic: 'Lewis structures', microtarget: 'Draw correct Lewis structures and formal charges.' },
      { orderIndex: 5, topic: 'VSEPR theory', microtarget: 'Predict molecular shape from electron pair geometry.' },
      { orderIndex: 6, topic: 'Hybridisation', microtarget: 'Identify hybridisation and shape of central atom.' },
      { orderIndex: 7, topic: 'Polarity and dipole moment', microtarget: 'Determine molecular polarity and dipole moment direction.' },
      { orderIndex: 8, topic: 'Molecular orbital theory', microtarget: 'Calculate bond order and magnetic behavior for simple molecules.' },
      { orderIndex: 9, topic: 'Hydrogen bonding', microtarget: 'Identify intermolecular and intramolecular hydrogen bonding.' },
      { orderIndex: 10, topic: 'Common bonding mistakes', microtarget: 'Avoid hybridisation-shape and polarity mistakes.' },
    ],
  },
  {
    templateKey: 'neet_chemistry_organic_basics',
    subject: 'Chemistry',
    chapter: 'Organic Chemistry Basics',
    displayName: 'Organic Chemistry Basics',
    aliases: ['organic chemistry', 'goc', 'general organic chemistry', 'iupac', 'isomerism'],
    topics: [
      { orderIndex: 1, topic: 'IUPAC nomenclature', microtarget: 'Name simple organic compounds using correct parent chain and suffix.' },
      { orderIndex: 2, topic: 'Electronic effects', microtarget: 'Apply inductive, resonance, hyperconjugation, and electromeric effects.' },
      { orderIndex: 3, topic: 'Reaction intermediates', microtarget: 'Compare stability of carbocations, carbanions, free radicals, and carbenes.' },
      { orderIndex: 4, topic: 'Acidity and basicity', microtarget: 'Predict acidity/basicity using electronic effects and resonance.' },
      { orderIndex: 5, topic: 'Isomerism basics', microtarget: 'Identify structural, geometrical, and optical isomerism basics.' },
      { orderIndex: 6, topic: 'Mechanism basics', microtarget: 'Identify nucleophiles, electrophiles, leaving groups, and reaction arrows.' },
      { orderIndex: 7, topic: 'Common GOC mistakes', microtarget: 'Avoid wrong resonance, stability, and acidity assumptions.' },
    ],
  },
  {
    templateKey: 'neet_chemistry_equilibrium',
    subject: 'Chemistry',
    chapter: 'Equilibrium',
    displayName: 'Equilibrium',
    aliases: ['equilibrium', 'ionic equilibrium', 'chemical equilibrium', 'ph', 'buffer', 'solubility product'],
    topics: [
      { orderIndex: 1, topic: 'Chemical equilibrium', microtarget: 'Write equilibrium expressions and understand dynamic equilibrium.' },
      { orderIndex: 2, topic: 'Equilibrium constant', microtarget: 'Use Kc and Kp and convert between them.' },
      { orderIndex: 3, topic: 'Le Chatelier principle', microtarget: 'Predict shift due to concentration, pressure, and temperature changes.' },
      { orderIndex: 4, topic: 'Acids and bases', microtarget: 'Classify acids and bases and calculate pH for simple systems.' },
      { orderIndex: 5, topic: 'Buffer solutions', microtarget: 'Understand buffer action and Henderson equation basics.' },
      { orderIndex: 6, topic: 'Solubility product', microtarget: 'Use Ksp to predict precipitation and solubility.' },
      { orderIndex: 7, topic: 'Common equilibrium mistakes', microtarget: 'Avoid wrong shift direction and pH calculation errors.' },
    ],
  },
];
